# Generated by Django 4.2.3 on 2023-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
