# Generated by Django 4.2.3 on 2023-07-25 00:00

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_eventphoto_eventfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.ImageField(upload_to=core.models.event_photo_path),
        ),
    ]
