# Generated by Django 4.2.3 on 2023-07-25 00:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_eventphoto_event_alter_eventphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to=core.models.event_file_path),
        ),
    ]
