# Generated by Django 4.2.3 on 2023-07-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_eventfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
    ]
