# Generated by Django 4.2.3 on 2023-08-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_venue_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
