# Generated by Django 4.2.3 on 2023-08-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_equipmentbrand_name_alter_equipmentmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbrand',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
