# Generated by Django 4.2.3 on 2023-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_equipmentbrand_name_alter_equipmentmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
