# Generated by Django 4.2.3 on 2023-08-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_client_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='client',
            new_name='customer',
        ),
    ]
